import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory-context";
import { calculateReportSummary, REPORT_PERIODS, type ReportPeriod } from "@/lib/reporting";

export default function ReportsScreen() {
  const router = useRouter();
  const { lots, movements, getProduct } = useInventory();
  const [period, setPeriod] = useState<ReportPeriod>("Semana");
  const report = useMemo(() => calculateReportSummary({ lots, movements, getProduct, period }), [getProduct, lots, movements, period]);
  const maxLoss = Math.max(report.expired, report.damaged, report.spoiled, 1);

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><Pressable accessibilityRole="button" accessibilityLabel="Voltar" onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#18211F" /></Pressable><Text style={styles.title}>Relatórios</Text><Text style={styles.subtitle}>Indicadores para reduzir perdas na operação.</Text><View style={styles.periods}>{REPORT_PERIODS.map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: period === item }} accessibilityLabel={`Filtrar relatório por ${item.toLowerCase()}`} onPress={() => setPeriod(item)} style={({ pressed }) => [styles.period, period === item && styles.periodActive, pressed && styles.pressed]}><Text style={[styles.periodText, period === item && styles.periodTextActive]}>{item}</Text></Pressable>)}</View><View style={styles.hero}><Text style={styles.heroLabel}>UNIDADES PERDIDAS · {period.toUpperCase()}</Text><Text style={styles.heroValue}>{report.total}</Text><Text style={styles.heroHelper}>Perdas registradas no período selecionado.</Text></View><View style={styles.grid}><Stat icon="event-busy" value={report.expired} label="Vencidos" color="#C73737" /><Stat icon="report-problem" value={report.damaged} label="Avariados" color="#D96816" /><Stat icon="mood-bad" value={report.spoiled} label="Estragados" color="#C73737" /><Stat icon="schedule" value={report.critical} label="Recebidos críticos" color="#C98A00" /></View><Text style={styles.section}>Destaques do período</Text><View style={styles.details}><Detail icon="trending-down" title="Produto com maior perda" value={report.leader} /><Detail icon="category" title="Categoria com maior perda" value={report.category} /><Detail icon="lightbulb-outline" title="Ação recomendada" value="Revisar lotes com até 5 dias" /></View><Text style={styles.section}>Distribuição de perdas</Text><View style={styles.chart}><Bar label="Vencidos" value={report.expired} max={maxLoss} color="#C73737" /><Bar label="Avariados" value={report.damaged} max={maxLoss} color="#D96816" /><Bar label="Estragados" value={report.spoiled} max={maxLoss} color="#9D3C3C" /></View></ScrollView></ScreenContainer>;
}

function Stat({ icon, value, label, color }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; value: number; label: string; color: string }) { return <View style={styles.stat}><MaterialIcons name={icon} size={19} color={color} /><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Detail({ icon, title, value }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; value: string }) { return <View style={styles.detail}><View style={styles.detailIcon}><MaterialIcons name={icon} size={20} color="#0B5D52" /></View><View style={styles.detailBody}><Text style={styles.detailTitle}>{title}</Text><Text style={styles.detailValue}>{value}</Text></View></View>; }
function Bar({ label, value, max, color }: { label: string; value: number; max: number; color: string }) { return <View style={styles.barRow}><Text style={styles.barLabel}>{label}</Text><View style={styles.barTrack}><View style={[styles.barFill, { width: `${Math.max(8, value / max * 100)}%`, backgroundColor: color }]} /></View><Text style={styles.barValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ page: { paddingTop: 14, paddingBottom: 28 }, back: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9", marginBottom: 15 }, title: { color: "#18211F", fontSize: 27, lineHeight: 34, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: "#60706C", fontSize: 13, marginTop: 2 }, periods: { flexDirection: "row", gap: 8, marginTop: 18 }, period: { paddingHorizontal: 15, paddingVertical: 9, borderRadius: 99, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#DFE8E4" }, periodActive: { backgroundColor: "#0B5D52", borderColor: "#0B5D52" }, periodText: { color: "#60706C", fontSize: 12, fontWeight: "800" }, periodTextActive: { color: "#FFFFFF" }, hero: { backgroundColor: "#0B5D52", borderRadius: 23, padding: 19, marginTop: 15 }, heroLabel: { color: "#BCE4D8", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, heroValue: { color: "#FFFFFF", fontSize: 43, lineHeight: 51, fontWeight: "900", marginTop: 3 }, heroHelper: { color: "#D4F2E9", fontSize: 11, lineHeight: 16 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 11 }, stat: { width: "47.8%", minHeight: 100, borderRadius: 18, padding: 13, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9" }, statValue: { color: "#18211F", fontSize: 23, fontWeight: "900", marginTop: 8 }, statLabel: { color: "#60706C", fontSize: 11, fontWeight: "700", marginTop: 1 }, section: { color: "#18211F", fontSize: 17, fontWeight: "800", marginTop: 24, marginBottom: 10 }, details: { backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#E5ECE9", overflow: "hidden" }, detail: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: "#EEF2F0" }, detailIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: "#EAF5F0", alignItems: "center", justifyContent: "center" }, detailBody: { flex: 1 }, detailTitle: { color: "#60706C", fontSize: 11, fontWeight: "700" }, detailValue: { color: "#18211F", fontSize: 13, fontWeight: "800", marginTop: 2 }, chart: { backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#E5ECE9", padding: 15, gap: 13 }, barRow: { flexDirection: "row", alignItems: "center", gap: 8 }, barLabel: { width: 69, color: "#60706C", fontSize: 11, fontWeight: "700" }, barTrack: { flex: 1, height: 9, borderRadius: 9, backgroundColor: "#EDF2F0", overflow: "hidden" }, barFill: { height: 9, borderRadius: 9 }, barValue: { width: 20, textAlign: "right", color: "#18211F", fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] } });
