import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ProductThumb, StatusPill, TapCard } from "@/components/inventory-ui";
import { ScreenContainer } from "@/components/screen-container";
import { daysUntil, formatDate, type InventoryLot } from "@/lib/inventory-data";
import { useInventory } from "@/lib/inventory-context";

type Filter = "Todos" | "Alerta" | "Hoje" | "3 dias" | "5 dias" | "10 dias" | "15 dias" | "Vencidos";
const filters: Filter[] = ["Todos", "Alerta", "Hoje", "3 dias", "5 dias", "10 dias", "15 dias", "Vencidos"];

export default function ExpiryScreen() {
  const router = useRouter(); const { lots, getProduct, alertLeadDays } = useInventory(); const [filter, setFilter] = useState<Filter>("Todos"); const [sort, setSort] = useState<"near" | "far" | "name" | "lot">("near");
  const filtered = useMemo(() => lots.filter((lot) => lot.currentQuantity > 0).filter((lot) => { const days = daysUntil(lot.expiryDate); if (filter === "Todos") return true; if (filter === "Alerta") return days >= 0 && days <= alertLeadDays; if (filter === "Hoje") return days === 0; if (filter === "Vencidos") return days < 0; const limit = Number.parseInt(filter, 10); return days >= 0 && days <= limit; }).sort((a, b) => { if (sort === "far") return daysUntil(b.expiryDate) - daysUntil(a.expiryDate); if (sort === "name") return (getProduct(a.productId)?.name ?? "").localeCompare(getProduct(b.productId)?.name ?? ""); if (sort === "lot") return a.code.localeCompare(b.code); return daysUntil(a.expiryDate) - daysUntil(b.expiryDate); }), [alertLeadDays, filter, getProduct, lots, sort]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={filtered} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.title}>Validades</Text><Text style={styles.subtitle}>Lotes organizados pela data mais próxima</Text><View style={styles.alertBanner}><MaterialIcons name="notifications-active" size={19} color="#0B5D52" /><Text style={styles.alertBannerText}>Avisos ativos para vencimentos em até <Text style={styles.alertBannerStrong}>{alertLeadDays} dias</Text>.</Text></View><FlatList data={filters} horizontal showsHorizontalScrollIndicator={false} keyExtractor={(item) => item} contentContainerStyle={styles.filters} renderItem={({ item }) => <Pressable onPress={() => setFilter(item)} style={({ pressed }) => [styles.chip, filter === item && styles.chipActive, pressed && styles.pressed]}><Text style={[styles.chipText, filter === item && styles.chipTextActive]}>{item === "Alerta" ? `Alerta (${alertLeadDays}d)` : item}</Text></Pressable>} /><View style={styles.sortRow}><Text style={styles.sortLabel}>Ordenar por</Text><Pressable onPress={() => setSort((current) => current === "near" ? "far" : current === "far" ? "name" : current === "name" ? "lot" : "near")} style={({ pressed }) => [styles.sortButton, pressed && styles.pressed]}><MaterialIcons name="sort" size={16} color="#0B5D52" /><Text style={styles.sortValue}>{sort === "near" ? "Validade mais próxima" : sort === "far" ? "Validade mais distante" : sort === "name" ? "Nome" : "Lote"}</Text></Pressable></View><Text style={styles.count}>{filtered.length} lotes no resultado</Text></>} renderItem={({ item }) => <ExpiryCard lot={item} product={getProduct(item.productId)} alertLeadDays={alertLeadDays} onPress={() => router.push({ pathname: "/lot/[id]", params: { id: item.id } })} />} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="event-available" size={32} color="#16794D" /><Text style={styles.emptyText}>Nenhum lote nesta seleção</Text></View>} /></ScreenContainer>;
}

function ExpiryCard({ lot, product, alertLeadDays, onPress }: { lot: InventoryLot; product: ReturnType<typeof useInventory>["getProduct"] extends (id: string) => infer R ? R : never; alertLeadDays: ReturnType<typeof useInventory>["alertLeadDays"]; onPress: () => void }) { if (!product) return null; return <TapCard onPress={onPress} style={styles.card}><ProductThumb source={product.image} /><View style={styles.cardBody}><View style={styles.cardTop}><Text style={styles.name} numberOfLines={1}>{product.name}</Text><StatusPill lot={lot} alertLeadDays={alertLeadDays} /></View><Text style={styles.meta}>{product.brand} · Lote {lot.code}</Text><Text style={styles.stock}>{lot.currentQuantity} unidades · {formatDate(lot.expiryDate)}</Text></View><MaterialIcons name="chevron-right" size={22} color="#92A09C" /></TapCard>; }

const styles = StyleSheet.create({ list: { paddingTop: 16, paddingBottom: 28 }, title: { color: "#18211F", fontSize: 27, lineHeight: 34, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: "#60706C", fontSize: 13, marginTop: 2 }, alertBanner: { marginTop: 14, borderRadius: 15, padding: 11, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#EAF5F0" }, alertBannerText: { flex: 1, color: "#426159", fontSize: 12, lineHeight: 16 }, alertBannerStrong: { color: "#0B5D52", fontWeight: "900" }, filters: { gap: 8, paddingVertical: 18 }, chip: { height: 35, justifyContent: "center", paddingHorizontal: 14, backgroundColor: "#FFFFFF", borderRadius: 99, borderWidth: 1, borderColor: "#DFE8E4" }, chipActive: { backgroundColor: "#0B5D52", borderColor: "#0B5D52" }, chipText: { color: "#52625D", fontSize: 12, fontWeight: "800" }, chipTextActive: { color: "#FFFFFF" }, sortRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, sortLabel: { color: "#4D5A56", fontSize: 13, fontWeight: "800" }, sortButton: { flexDirection: "row", alignItems: "center", gap: 5, maxWidth: "65%" }, sortValue: { color: "#0B5D52", fontSize: 12, fontWeight: "800" }, count: { color: "#71817C", fontSize: 12, fontWeight: "700", marginBottom: 9 }, card: { minHeight: 86, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9", borderRadius: 19, padding: 12, flexDirection: "row", gap: 11, alignItems: "center", marginBottom: 9 }, cardBody: { flex: 1 }, cardTop: { flexDirection: "row", gap: 5, justifyContent: "space-between", alignItems: "flex-start" }, name: { color: "#18211F", fontSize: 14, lineHeight: 19, fontWeight: "800", flex: 1 }, meta: { color: "#60706C", fontSize: 11, marginTop: 2 }, stock: { color: "#4A5954", fontSize: 12, fontWeight: "700", marginTop: 6 }, empty: { alignItems: "center", padding: 38, backgroundColor: "#FFFFFF", borderRadius: 20, gap: 8 }, emptyText: { color: "#60706C", fontWeight: "700" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
