import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory-context";

export default function MoreScreen() {
  const router = useRouter(); const { employeeName, signOut } = useInventory();
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.page}><Text style={styles.title}>Mais</Text><Text style={styles.subtitle}>Acompanhe a operação e ajuste preferências.</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{employeeName.split(" ").map((part) => part[0]).slice(0, 2).join("")}</Text></View><View><Text style={styles.profileName}>{employeeName}</Text><Text style={styles.profileRole}>Controle de estoque</Text></View></View><View style={styles.menu}><MenuItem icon="history" title="Histórico" description="Entradas, baixas e responsáveis" onPress={() => router.push("/history")} /><MenuItem icon="insights" title="Relatórios" description="Perdas e indicadores do período" onPress={() => router.push("/reports")} /><MenuItem icon="notifications-active" title="Configurações" description="Alertas de validade e notificações" onPress={() => router.push("/settings")} /></View><Pressable onPress={signOut} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><MaterialIcons name="logout" size={20} color="#C73737" /><Text style={styles.logoutText}>Encerrar sessão</Text></Pressable></View></ScreenContainer>;
}

function MenuItem({ icon, title, description, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; description: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.menuItem, pressed && styles.pressed]}><View style={styles.menuIcon}><MaterialIcons name={icon} size={22} color="#0B5D52" /></View><View style={styles.menuText}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDescription}>{description}</Text></View><MaterialIcons name="chevron-right" size={23} color="#92A09C" /></Pressable>; }

const styles = StyleSheet.create({ page: { paddingTop: 16 }, title: { color: "#18211F", fontSize: 27, lineHeight: 34, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: "#60706C", fontSize: 13, marginTop: 2 }, profile: { marginTop: 24, backgroundColor: "#DDF1EA", borderRadius: 22, padding: 16, flexDirection: "row", alignItems: "center", gap: 12 }, avatar: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "#0B5D52" }, avatarText: { color: "#FFFFFF", fontWeight: "900", fontSize: 14 }, profileName: { color: "#18211F", fontSize: 16, fontWeight: "800" }, profileRole: { color: "#4D645E", fontSize: 12, marginTop: 3 }, menu: { marginTop: 16, backgroundColor: "#FFFFFF", borderRadius: 22, borderWidth: 1, borderColor: "#E5ECE9", overflow: "hidden" }, menuItem: { minHeight: 77, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "#EEF2F0" }, menuIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: "#EAF5F0", alignItems: "center", justifyContent: "center" }, menuText: { flex: 1 }, menuTitle: { color: "#18211F", fontSize: 15, fontWeight: "800" }, menuDescription: { color: "#60706C", fontSize: 12, marginTop: 3 }, logout: { height: 52, borderRadius: 16, marginTop: 18, backgroundColor: "#FDEBEB", flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 }, logoutText: { color: "#C73737", fontWeight: "800", fontSize: 14 }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] } });
