import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ProductThumb, TapCard } from "@/components/inventory-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory-context";

export default function ProductsScreen() {
  const router = useRouter();
  const { products, lots } = useInventory();
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => products.filter((product) => { const allLots = lots.filter((lot) => lot.productId === product.id); const target = `${product.name} ${product.brand} ${product.barcode} ${allLots.map((lot) => lot.code).join(" ")}`.toLowerCase(); return target.includes(query.trim().toLowerCase()); }), [lots, products, query]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={filtered} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.heading}><View><Text style={styles.title}>Produtos</Text><Text style={styles.subtitle}>Catálogo consolidado por item</Text></View><Pressable onPress={() => router.push("/(tabs)/scanner")} style={({ pressed }) => [styles.add, pressed && styles.pressed]}><MaterialIcons name="add" size={24} color="#FFFFFF" /></Pressable></View><View style={styles.search}><MaterialIcons name="search" size={20} color="#60706C" /><TextInput value={query} onChangeText={setQuery} style={styles.searchInput} placeholder="Nome, marca, código ou lote" placeholderTextColor="#80908A" returnKeyType="search" /><Pressable onPress={() => setQuery("")} hitSlop={10}>{query ? <MaterialIcons name="close" size={18} color="#60706C" /> : null}</Pressable></View><Text style={styles.count}>{filtered.length} produtos cadastrados</Text></>} renderItem={({ item }) => { const productLots = lots.filter((lot) => lot.productId === item.id); const total = productLots.reduce((sum, lot) => sum + lot.currentQuantity, 0); return <TapCard onPress={() => router.push({ pathname: "/product/[id]", params: { id: item.id } })} style={styles.card}><ProductThumb source={item.image} /><View style={styles.cardBody}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.brand} · {item.volume}</Text><Text style={styles.stock}>{total} unidades · {productLots.length} {productLots.length === 1 ? "lote" : "lotes"}</Text></View><MaterialIcons name="chevron-right" size={23} color="#92A09C" /></TapCard>; }} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="search-off" size={30} color="#60706C" /><Text style={styles.emptyText}>Nenhum produto encontrado</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { paddingTop: 16, paddingBottom: 28 }, heading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 19 }, title: { color: "#18211F", fontSize: 27, lineHeight: 34, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: "#60706C", fontSize: 13, marginTop: 1 }, add: { width: 45, height: 45, borderRadius: 15, backgroundColor: "#0B5D52", alignItems: "center", justifyContent: "center" }, search: { height: 51, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#DFE8E4", borderRadius: 16, flexDirection: "row", alignItems: "center", paddingHorizontal: 14 }, searchInput: { flex: 1, color: "#18211F", fontSize: 14, paddingVertical: 10, marginLeft: 9 }, count: { color: "#71817C", fontSize: 12, fontWeight: "700", marginTop: 12, marginBottom: 10 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9", borderRadius: 19, padding: 12, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 9 }, cardBody: { flex: 1 }, name: { color: "#18211F", fontSize: 15, lineHeight: 20, fontWeight: "800" }, meta: { color: "#60706C", fontSize: 12, marginTop: 3 }, stock: { color: "#4A5954", fontSize: 12, fontWeight: "700", marginTop: 7 }, empty: { alignItems: "center", padding: 38, backgroundColor: "#FFFFFF", borderRadius: 20, gap: 8 }, emptyText: { color: "#60706C", fontWeight: "700" }, pressed: { opacity: 0.75, transform: [{ scale: 0.96 }] } });
