import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ProductThumb, StatusPill, TapCard } from "@/components/inventory-ui";
import { ScreenContainer } from "@/components/screen-container";
import { formatDate } from "@/lib/inventory-data";
import { useInventory } from "@/lib/inventory-context";

export default function ProductDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { getProduct, lotsForProduct } = useInventory(); const product = getProduct(id); const lots = lotsForProduct(id).sort((a, b) => a.expiryDate.localeCompare(b.expiryDate)); if (!product) return <ScreenContainer className="p-5"><Text>Produto não encontrado.</Text></ScreenContainer>; const total = lots.reduce((sum, lot) => sum + lot.currentQuantity, 0); return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={lots} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} ListHeaderComponent={<><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#18211F" /></Pressable><View style={styles.hero}><ProductThumb source={product.image} size="large" /><View style={styles.heroBody}><Text style={styles.name}>{product.name}</Text><Text style={styles.brand}>{product.brand} · {product.volume}</Text><Text style={styles.total}>{total} unidades disponíveis</Text></View></View><View style={styles.divider} /><Text style={styles.sectionTitle}>Lotes cadastrados</Text><Text style={styles.sectionSub}>{lots.length} lotes com condições independentes</Text></>} renderItem={({ item }) => <TapCard onPress={() => router.push({ pathname: "/lot/[id]", params: { id: item.id } })} style={styles.card}><View style={styles.cardHead}><View><Text style={styles.lotCode}>Lote {item.code}</Text><Text style={styles.cardMeta}>{item.currentQuantity} unidades · {formatDate(item.expiryDate)}</Text></View><StatusPill lot={item} /></View><View style={styles.quality}><MaterialIcons name="verified" size={15} color="#60706C" /><Text style={styles.qualityText}>{item.quality}</Text><MaterialIcons name="chevron-right" size={21} color="#92A09C" style={styles.chevron} /></View></TapCard>} /></ScreenContainer>; }
const styles = StyleSheet.create({ list: { paddingTop: 14, paddingBottom: 28 }, back: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9", marginBottom: 16 }, hero: { flexDirection: "row", alignItems: "center", gap: 15 }, heroBody: { flex: 1 }, name: { color: "#18211F", fontSize: 22, lineHeight: 28, fontWeight: "800", letterSpacing: -0.5 }, brand: { color: "#60706C", fontSize: 13, marginTop: 4 }, total: { color: "#0B5D52", fontSize: 13, fontWeight: "800", marginTop: 10 }, divider: { height: 1, backgroundColor: "#DFE8E4", marginVertical: 23 }, sectionTitle: { color: "#18211F", fontSize: 18, fontWeight: "800" }, sectionSub: { color: "#60706C", fontSize: 12, marginTop: 3, marginBottom: 11 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5ECE9", borderRadius: 18, padding: 15, marginBottom: 9 }, cardHead: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, lotCode: { color: "#18211F", fontSize: 15, fontWeight: "800" }, cardMeta: { color: "#60706C", fontSize: 12, marginTop: 4 }, quality: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 12 }, qualityText: { color: "#60706C", fontSize: 12, fontWeight: "700" }, chevron: { marginLeft: "auto" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
